---
apiVersion: v1
kind: Secret
metadata:
  name: elastic
  namespace: kube-system
type: Opaque
data:
  ELASTIC_CLOUD_ID: ...
  ELASTIC_CLOUD_AUTH: ...
  ELASTICSEARCH_HOST: ...
  ELASTICSEARCH_PORT: ...
  KIBANA_HOST: ...
  ELASTIC_USERNAME: ...
  ELASTIC_PASSWORD: ...

